# Generated by Django 3.1.7 on 2021-04-08 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('post_work', '0001_initial'),
        ('find_work', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='findwork',
            name='user',
            field=models.ForeignKey(db_column='User', on_delete=django.db.models.deletion.CASCADE, to='post_work.postwork'),
        ),
    ]
