# Generated by Django 3.1.7 on 2021-04-09 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post_work', '0002_auto_20210409_1918'),
        ('find_work', '0002_findwork_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='findwork',
            name='user',
            field=models.OneToOneField(db_column='User', on_delete=django.db.models.deletion.CASCADE, to='post_work.postwork'),
        ),
    ]
